### ISSUE TITLE
apparent bias between ATM data and single frequency GPS data compilation

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GCNet_positions#4]
according to the [ATM data v1 user guide](https://nsidc.org/sites/default/files/blatm2-v001-userguide.pdf) and the [v2 data guide](https://nsidc.org/sites/default/files/ilatm2-v002-userguide_0.pdf) ATM heights are "above WGS84 ellipsoid", which I think is the same as for the single frequency GPS data compilation. 

Yet, the single frequency GPS elevations are often lower than the ATM data.

Here's an example that includes both 'handheld' elevations, mainly from Koni Steffen's field notes, and monthly averages from the GEUS GC-Net data. The difference in this case is the single frequency GPS data are mostly ca. 60 m lower.

![Crawford Point 1](https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/assets/32133350/aa1ad788-ab05-4b0a-99b4-97b1a0f60148)

or mostly ca. 40 m lower for  single frequency GPS data at Saddle

![Saddle](https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/assets/32133350/78de45d1-d1e2-4eac-85a1-886eb037567e)

for Swiss Camp, the monthly averages of single frequency GPS data from the GEUS AWS are ca. 50 m lower. However the nearest point has moved downslope so I should search by an annually varying position.

![Swiss Camp](https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/assets/32133350/637099a4-98e2-46d5-9728-0956d4e36b38)

Yet, it's not always that the  single frequency GPS data are lower, e.g. Summit, below so I am thinking the single frequency data are unreliable BUT the monthly averages from single frequency should not be biased?

![Summit](https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/assets/32133350/4457270b-0d2f-4518-86b8-40b1fa998fb2)

Find all the plots in [https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/tree/main/ATM/Figs](https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/tree/main/ATM/Figs)

**Comment by BaptisteVandecrux** [comment]
Great job, thanks!
I'm not surprised that the handheld GPSs have 30-50 m accuracy.
The difference between the ATM and the GEUS measurements are more puzzling!

**Comment by jasonebox** [comment]
so I learned that the AWS and handheld GPS output "elevation" above mean sea level and that's of course not the same as height above ellipsoid. To adjust the ATM data to elevation, the difference in ellipsoidal height and that of mean sea level is obtained by obtaining geoid height using e.g. KMS Trans software that JJ@GEUS.DK has used. I plan to look into running KMS Trans.

**Comment by jasonebox** [comment]
got confirmation from jj@geus.dk tjat the correction from ellipsoidal height to orthometric height makes sense, so am proceeding
