### ISSUE TITLE
Swiss Camp elevation reconstruction by a german team

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/GCNet_positions#6]
https://epic.awi.de/id/eprint/55943/

![image](https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/assets/35140661/75dc8210-f390-4a17-a905-65c1f6fd5b0d)

**Comment by jasonebox** [comment]
these data are now accounted, see https://github.com/GEUS-Glaciology-and-Climate/GCNet_positions/blob/659d86dee514df369cf8ea195c517f2252dc9788/analyze_AWS_elevs_including_ATM_v3.py#L388
