### ISSUE TITLE
git conflict

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GCNet_positions#7]
I've taken the work forward by bringing in M. Stober's measurements at SWC and JAR, and may have some other updates, but am unable to push the updates!

**Comment by BaptisteVandecrux** [comment]
I've put you as admin of the repo, so if it was a permission issue it should be solved.

But if it is a git conflict issue, the best is to push your updates into a new branch and open a pull request. Then we can resolve the conflict together.

**Comment by jasonebox** [comment]
I cloned and copied over new content and pushed, all ok now
